services:
  - type: web
    name: restaurant-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # set this in Render dashboard with your Atlas DB URI
